### ISSUE TITLE
dev下无法显示tooltip和popover组件,build后展示触发上述组件后网页就崩溃了

### ISSUE THREAD

**Issue by mutunx** [Saszr/rfmo#12]
在`dev`模式下
- 鼠标移动到左边热力图的方块没有显示`tooltip`
- 鼠标移动到`MemoCard`上面的`Popover`组件也没有显示

在`build`后打开页面
- 移动到上述组件就要么就是页面崩溃要么就是页面鼠标一直处于`pointer`样式,什么也点不了

不知道是不是我配置的有问题,填写内容和`tag`发送都没问题
很喜欢这个项目,页面设计的很漂亮,想深入学习学习

**Comment by Saszr** [comment]
React 18 antd 旧版本的问题，fix 了 https://github.com/Saszr/rfmo/commit/6afcc7a77c7fe39029c8b4ea9b2fd3fb7360c037
现在看之前写的有蛮多不合理的地方 😭
