### ISSUE TITLE
很棒的一个项目！

### ISSUE THREAD

**Issue by imhan0cn** [Saszr/rfmo#3]
rfmo 是一个非常棒的项目，之前了解过flomo，一直想在服务器自己部署一个类似的笔记服务，但自身技术有限没写好，无意中发现了这个项目，我希望可以请作者喝一杯咖啡（如果允许的话，可以在readme界面放上相关打赏链接），给作者一些鼓励，为开源做出贡献。

**Comment by Saszr** [comment]
👋 项目阶段蛮初级的，受之有愧，完成度高一点会挂个打赏链接。readme 相关链接里有类似项目的推荐。
这个项目一开始的冲动，也是一方面自己也有这个类似的需求，然后本身做这个东西也是个学习提升的过程，开源分享也是让自己有个正向的反馈能够坚持下去。
既然有学习的目的，后面也会看一下客户端相关的，rn / flutter / 小程序 / electron / tauri ～
现在还是主要弄这个网页端
